# Модель системы учета товаров супермаркета

@startuml

(*) --> "Получить новый товар" as A
--> "Добавить товар на склад" as B
--> "Аудит товаров на складе" as C
--> "Разместить товары в магазине" as D
--> "Аудит товаров в магазинах" as E
--> "Произвести оплату с помощью кассового аппарата" as F
--> (*)

@enduml
