# Модель системы учета товаров супермаркета

@startuml

class Warehouse {
  +goods: List;
  +auditors: List;
  +addGoods(goods: Goods): void;
  +removeGoods(goods: Goods): void;
  +auditGoods(): void;
  }

class Goods {
  +id: int;
  +name: string;
  +quantity: int;

  +getId();
  +getName();
  +getQuantity();
  }

class Staff {

  +id: int;
  +name: string;

  +getId();
  +getName();
  }

class Store {

  +goods: List;
  +placement: List;
  +auditors: List;

  +addGoods(goods: Goods): void;
  +removeGoods(goods: Goods): void;
  +placeGoods(goods: Goods, placement: Placement): void;
  +auditGoods();
  }

class Placement {

  +id: int;
  +location: string;

  +getId();
  +getLocation();
  }

class CashRegister {

  +processPayment(amount: double): void; 
  
  +print checks();
  +accountingForSoldGoods();
  }

Goods --> Warehouse
Warehouse --> Staff
Goods --> Store
Store --> Placement
Placement --> Staff

@enduml
