@startuml
title Вычисление корней квадратного уравнения
start
:Ввести коэффициенты а, b, c;
:Привести к каноничному виду: a⋅x^2+b⋅x+c=0;
switch(Вычисляем дискриминант)
case(D < 0)
:Корней нет;
detach
case(D = 0)
:Находим один корень по формуле:
x = -b/(2*a);
case(D>0)
:Находим 2 корня по формуле: 
x1 = (-b + sqrt(b^2-4*a*c))/2*a
x2 = (-b - sqrt(b^2-4*a*c))/2*a;
endswitch
: Вывод ответа;
stop
@endum
