@startuml

title Получение денег в банкомате
start
:Приложить карту к считывателю;
:Запросить пароль;
if(Пароль верный) then (да)
    :Разрешить доступ;
    :Запросить сумму для снятия;
     if(Денег на счете достаточно) then (Да)
     :Выдать деньги;
      stop
     else (Нет)
     :Ошибка: Сумма недоступна для вывода;
     detach
     endif
else (нет) 
    :Ошибка: неверный пароль;
     detach 
endif
@endum
