@startuml                                     
Пользователь --> ПК: Запись на диск          
ПК --> Диск: Запись прошла успешно             
Пользователь --> ПК: Запрос на верификацию     
ПК --> Диск: Верификация прошла успешно        
@enduml                                        
                                               
-----------------------------------------------
@startuml
Пользователь --> ПК: Запись на диск
ПК --> Пользователь: Сообщение об ошибке
ПК --> Диск: Запись не выполнена
@enduml

-----------------------------------------------

@startuml
Пользователь --> ПК: Запись на диск
ПК --> Пользователь: Сообщение об ошибке
Пользователь --> Диск: Очистка диска
Пользователь --> ПК: Запись на диск
ПК --> Диск: Запись выполнена успешно
@enduml

-----------------------------------------------
@startuml
Пользователь --> ПК: Запись на диск
ПК --> Пользователь: Диск поврежден
ПК --> Диск: Запись не выполнена
@enduml

-----------------------------------------------

@startuml
Пользователь --> ПК: Запись на диск
ПК --> Диск: Верификация
Диск --> Пользователь: Имеются ошибки
ПК --> Диск: Запись прошла успешно
@enduml
